on: [push, pull_request]

name: Build

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features
      - name: Check `cargo fmt` was run
        run: |
          cd protocol_codegen
          cargo fmt -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all
